### ISSUE TITLE
Adding unit MN to conversion_rules.php

### ISSUE THREAD

**Issue by tolarv** [dbauer-ets/moodle-qtype_formulas#111]
We would need to expand support for SI units. We often use the force unit N, but also multiples of kN and MN. In moodle formulas we only get kN and N, not MN.

Please add this unit in the conversion_rules.php file:

N: **M** k m u n p f;

**Comment by PhilippImhof** [comment]
Thanks for submitting this. It should not be a big deal to add that, so I will try to do it when preparing the next release.
