### ISSUE TITLE
Possible Tranlsation typo

### ISSUE THREAD

**Issue by N7Remus** [dbauer-ets/moodle-qtype_formulas#140]
In translations 
$string['incorrectfeedback_help'] = 'This feedback will be show to students that don\'t get any mark at this part. It can include global and locals variables that will be replaced by their values';

global and locals variables
should be 
global and local variables

**Comment by PhilippImhof** [comment]
Thanks for your feedback. We will fix that in one of the upcoming releases.

**Comment by N7Remus** [comment]
Found an other one at error_validation_eval :
Try evalution error!
->       evaluation

**Comment by PhilippImhof** [comment]
Thanks! This message will by gone with the next major version, but I might still change it when preparing the next bugfix release.

**Comment by N7Remus** [comment]
Im nearly finished with all the hungarian translations. (please include that too)

**Comment by PhilippImhof** [comment]
> (please include that too)

Include what? The "evalution error" or did you find more?

It's nice to see you took the time to translate our plugin to Hungarian; thanks!

Please note (in case you did not know) that you must submit your translation via [AMOS](https://lang.moodle.org/local/amos/view.php), as plugins are not supposed to be shipped with multiple languages.

**Comment by PhilippImhof** [comment]
@N7Remus If you have spotted any other typos / language errors that you would like to have fixed, please tell me. I have PR #142 ready to be merged.

**Comment by N7Remus** [comment]
I think you fixed them all. (Also i sent the translations with AMOS.)
Have a nice day!

**Comment by PhilippImhof** [comment]
Perfect! Thanks for your contribution!
