### ISSUE TITLE
Small bug?

### ISSUE THREAD

**Issue by dbauer-ets** [dbauer-ets/moodle-qtype_formulas#146]
Philipp,

Here's a small bug. When there is no space after the < sign, instantiate does not work. It is not a big bug for those who know about this, but it is confusing for those who don't know.

Global variables
a = 2;
b = a <1 ? 0 : 1;    # no space between "<" and "1"

Instantiate
invalidparameter
Invalid parameter value detected

compared to:

Global variables
a = 2;
b = a < 1 ? 0 : 1;    # with a space between "<" and "1"

Instantiate
works properly

**Comment by PhilippImhof** [comment]
You are right. This has been fixed in #138 and the fix will be in the next release. I'll wait for Moodle 4.4 to be out before publishing it, so that will be next Monday.
