### ISSUE TITLE
Login to dynamiccourseware.org

### ISSUE THREAD

**Issue by MatthiasBartscht** [dbauer-ets/moodle-qtype_formulas#150]
Hi everybody,

Matthias here. I'm a teacher for electrical engineering and math on a professional school in Germany. I started using the formulas plugin (where you did a great job). And since I'm learning I often need the documentation @ dynmiccourseware.org. But I don't have access anymore. I need to login, but have no credentials or am I missing something?

Thanks in advance.

With best regards from Germany
Matthias

**Comment by PhilippImhof** [comment]
Hello Matthias

Thanks for your positive feedback. I have just tried accessing the [documentation](https://dynamiccourseware.org/course/index.php?categoryid=10) and cannot reproduce your problem, even in a clean browser set-up. I am automatically logged in and do not have to enter a password.

Let's wait for @dbauer-ets who actually runs that server and does a tremendous work maintaining all the docs.

**Comment by MatthiasBartscht** [comment]
It's working now, but I'm at home. I tried to connect from the internet connection of the school and I know it is very restricted. E.g. if I'm on youtube, all comments are not visible or I couldn't even login into google or use their fonts/cdn. So I think that was the problem.

Thanks for your help and sorry for the inconvenience.

With best regards
Matthias

**Comment by dbauer-ets** [comment]
Hello Matthias,

Recently, I modified the homepage of the website dynamiccourseware.org, and unfortunately, I slightly messed it up. While I work on fixing it, you might need to click on the "Log in" link in the top right corner of the window. The username and password remain the same: "student" and "Formulas.1".
![image](https://github.com/user-attachments/assets/33f5da52-670f-474e-a857-1bcabcacdaf9)
