### ISSUE TITLE
Inconsistency verifying student answer

### ISSUE THREAD

**Issue by nadavkav** [dbauer-ets/moodle-qtype_formulas#30]
When asking students to input the decimal fraction of randomly generated numbers based on the following syntax: 
`{a1}•10-{b1}=  {_0}`
They inconsistently verify as wrong answer, where they should be verified as correct ones.
![image](https://user-images.githubusercontent.com/231168/150696345-f9360b8b-a2ef-48db-9cd1-a6a303b5279a.png)
Tested with latest stable version from moodle.org/plugins repository, with a Moodle 3.9 stable version.

Attached is a link to a formulas question XML export, for testing:
https://gist.github.com/nadavkav/bb04e7e76a0d207f9970148fa184f7c7

**Comment by PhilippImhof** [comment]
You use `_err == 0` as a grading criterion. However, when using decimal numbers, this often leads to problems. See https://stackoverflow.com/questions/9508518/why-are-these-numbers-not-equal for an explanation. I suggest, you use another criterion, e.g. `_err <= 0.0001` (or similar) or by using the relative error.
