### ISSUE TITLE
decbin() and the like are not working

### ISSUE THREAD

**Issue by PhilippImhof** [dbauer-ets/moodle-qtype_formulas#43]
Reported in the [comments](https://moodle.org/plugins/qtype_formulas)
> Does anyone know why formulas no longer recognizes the decbin or decoct function?

A quick check

```
a = decbin(15);
```

yields: 
`Try evalution error! 1: Variable 'decoct' has not been defined. in substitute_vname_by_variables` 

Similar errors occur for `decoct()`, `octdec()` and `bindec()`. 

The problem exists **at least** since 4.91.

**Comment by jmvedrine** [comment]
Hello, to my best knowledge these functions have never been available in questions. If somebody had them working most likely the code was customized.

**Comment by PhilippImhof** [comment]
Thanks for confirming my impression. The history of `variables.php` shows that there have been no changes to the relevant part in the last 8 years.
