### ISSUE TITLE
sort() function not always working correctly

### ISSUE THREAD

**Issue by PhilippImhof** [dbauer-ets/moodle-qtype_formulas#48]
## Description of bug / unexpected behavior

* `sort(["4","3","A","a","B","2","1","b","c","C"]) --> ["A","B","C","a","b","c","1","2","3","4"]`, i.e. the letters come before the numbers.
* `sort(["B","C","A","B"]) --> ["A","B","C"]`, i.e. when two (or more) members are equal, they are merged into one member in the sorted array.
* `sort(["B","3","1","0","A","C","c","b","2","a"]) --> ["B","3","1","0","A","C","c","b","2","a"]`, i.e. the "0" element seems to interfere with the sorting.

## Expected behavior

* `sort(["4","3","A","a","B","2","1","b","c","C"]) --> ["1","2","3","4","A","B","C","a","b","c"]`, i.e. the numbers come first.
* `sort(["B","C","A","B"]) --> ["A","B","B","C"]`
* `sort(["B","3","1","0","A","C","c","b","2","a"]) --> ["0","1","2","3","A","B","C","a","b","c"]`

## More information

* https://moodle.org/mod/forum/discuss.php?d=405293
* https://dynamiccourseware.org/course/view.php?id=31&section=56.

**Comment by PhilippImhof** [comment]
All problems are created here:

https://github.com/FormulasQuestion/moodle-qtype_formulas/blob/df932527c824da0b0569cafa186929d01435fae2/variables.php#L1266-L1267

The funktion `ksort()` would accept a flag for a more natural sort order, but it is not used here. 

When calling `sort()` with two lists, the second is used as keys. (If it is called with one list, the list is duplicated and used once as keys, once as values.) However, array keys must be unique, so if the same key appears multiple times, only the last occurrence will be preserved. That explains why duplicated elements are missing.

**Comment by dbauer-ets** [comment]
<p>Hello Philipp,</p>
<p>In PHP, we have:<br>
    <br>
    $numbers = array(-3,-2,4,2,3,1,0,-1,-4,5);<br>
    $stings = array("-3","-2","B","2","3","1","0","-1","b","a","A");<br>
    $mixed = array("-3",-2,B,"2",3,1,"0","-1","b",a,"A");<br>
    sort($numbers); ⇒ [<span style="color:#0000FF;">-4,-3,-2,-1</span>,0,1,2,3,4,5]<br>
    sort($stings); ⇒ [<span style="color:#0000FF;">-3,-2,-1</span>,0,1,2,3,A,B,a,b]<br>
    sort($mixed); ⇒ [-3,-2,-1,0,2,A,B,a,b,1,3] # Inconsistent ordering of the positive integers<br>
    <br>
    In the Formulas question, we have:<br>
    <br>
    sort([-3,-2,4,2,3,1,0,-1,-4,5]) ⇒ [<span style="color:#FF0000;"><b>-1,-2,-3,-4</b></span>,0,1,2,3,4,5]<br>
    sort(["-3","-2","B","2","3","1","0","-1","b","a","A"]) ⇒ [<span style="color:#FF0000;"><b>-1,-2,-3</b></span>,0,1,2,3,A,B,a,b]<br>
    sort(["-3",-2,B,"2",3,1,"0","-1","b",a,"A"]) ⇒ # Not permitted
</p>

<p>
    I think the sort() function of the Formulas plugin should be modified so that the sorting of negative numbers is the same as PHP, and perhaps also that the sorting of strings representing negative numbers is the same as PHP.
</p>
<p>
  A user would like to be able to sort numbers in this way: <a href="https://moodle.org/mod/forum/discuss.php?d=446405" target="_blank">Moodle Forum➚</a>.
</p>
<p>What do you think?</p>

**Comment by PhilippImhof** [comment]
Thanks for spotting this. The sorting is consistent with PHP when comparing it to `natsort()` instead of `sort()`. However, I fully agree that it is counter-intuitive. If I had thought of adding a test case with negative numbers when I fixed the function, I would most certainly not have made it like this :) A PR is on the way, checks are running just now.

**Comment by dbauer-ets** [comment]
Philipp,

Je viens d'ajouter des commentaires à
https://github.com/FormulasQuestion/moodle-qtype_formulas/pull/94.

Dominique


Le sam. 6 mai 2023, à 05 h 05, Philipp Imhof ***@***.***> a
écrit :
