### ISSUE TITLE
Check variables instantiation not work

### ISSUE THREAD

**Issue by vel21ripn** [dbauer-ets/moodle-qtype_formulas#63]
## Description of bug / unexpected behavior

"Check variables instantiation" not working after updating to version 2022112700

When you click on the "instantiate" button, the message appears
````
TypeError 

column.definition is undefined
````

In version 2020061900 "Check variables instantiation" works.

## How to reproduce the issue

Create a simple quest:

Random variables:  a={1:3}; b={1:3};
Global variables: c=a\*b
Question text: how much is {=a}*{=b}

v2020061900 question/type/formulas/instantiate.php  return json
````
{
  "names": {
    "random": [
      "a",
      "b"
    ],
    "global": [
      "c"
    ],
    "local0": [],
    "answer0": [
      "@1"
    ]
  },
  "lists": [
    {
      "random": [
        1,
        2
      ],
      "global": [
        2
      ],
      "local0": [],
      "answer0": [
        [
          2
        ]
      ]
    }
  ],
  "size": 1,
  "maxdataset": 4,
  "errors": [
    ""
  ]
}
````

v2022112700 lib/ajax/service.php?sesskey=Y2qDOO70dr&info=qtype_formulas_instantiate return json
````
[
  {
    "error": false,
    "data": {
      "status": "ok",
      "data": [
        {
          "randomvars": [
            {
              "name": "a",
              "value": "2"
            },
            {
              "name": "b",
              "value": "1"
            }
          ],
          "globalvars": [
            {
              "name": "c",
              "value": "2"
            }
          ],
          "parts": [
            []
          ]
        }
      ] } }
]
````

* Moodle version: 3.9.18+ (Build: 20221216)
* Plugin version: 2022112700
* PHP version: 7.4.24
* Browser: Firefox, chrome

**Comment by vel21ripn** [comment]
The error appeared since the commit 9ff4328f780b4a040d53a39946eae897e77cd975
- new interface for instantiation check

**Comment by PhilippImhof** [comment]
Thanks for the report. Do you get an error message?

**Comment by PhilippImhof** [comment]
Nevermind. Pretty sure I found the problem, will fix it soon.
