### ISSUE TITLE
sigfig() function in a map() function

### ISSUE THREAD

**Issue by Vinz80** [dbauer-ets/moodle-qtype_formulas#69]
## Description of bug / unexpected behavior

After the upgrade from version 4.43 to version 5.1.1, one particular thing doesn't work anymore with the sigfig() function.
This line doesn't work anymore :
liste = map("sigfig",[2.123,3.568],3);

## Expected behavior
{liste[0]} does display 2.12
{liste[1]} does display 3.57

## How to reproduce the issue
Try the xml attached file.
When we type the code line in version 5.1.1, there is an error message : Exception : Call to undefined function sigfig()

## Environment

* Moodle version: 3.11.2 or 4.0.6
* Plugin version: 5.1.1
* PHP version: 7.4.33
* Browser: Firefox

[quiz-[B2-SP-CO] S06_Oscillateurs 2020-sigfig() in map()-20230213-1324.zip](https://github.com/FormulasQuestion/moodle-qtype_formulas/files/10722288/quiz-.B2-SP-CO.S06_Oscillateurs.2020-sigfig.in.map.-20230213-1324.zip)

**Comment by PhilippImhof** [comment]
Thanks for reporting. This seems to be broken since 5.0.1 at least. I will fix it soon.

**Comment by PhilippImhof** [comment]
Just to let you know that I have found the root cause of the bug and it is already fixed locally. I am running a few tests and think I can release a bugfix update soon.
