### ISSUE TITLE
Binomialcdf in Formulas Update

### ISSUE THREAD

**Issue by jotroT** [dbauer-ets/moodle-qtype_formulas#76]
Hi all, 

Dominique and Philipp are doing a great job with the maintenance of formulas-qt especially with the latest updates including normcdf()!!

I would like to suggest to include in further updates the function **binomialcdf**, e.g. as described in the attached file!

To my own purposes I declared for binomialcdf a return-value -1, if the parameters  are not consistent (which could be deleted). Obviously it should be pasted into **variables.php** after **ncr()** and as well appear in the lists of functions and where the parameter-list is dealt with :-)
As well there could be in a similar way other probability distributions as PoissonP/Cdf etc.! 

[binomial.txt](https://github.com/FormulasQuestion/moodle-qtype_formulas/files/10797936/binomial.txt)

**Comment by PhilippImhof** [comment]
Thanks for the positive feedback and the suggestion. I will gladly include that in the next update.
