### ISSUE TITLE
gcd() in Formulas Update

### ISSUE THREAD

**Issue by jotroT** [dbauer-ets/moodle-qtype_formulas#77]
Hi all,
I would like to suggest a change of gcd() in further versions [like it is realised by TInspire, or described in WIKIPEDIA]:
Now gcd(0,8) returns 1, but should return 8!
So please change the code-line
<code>if ($a == 0 xor $b == 0) {   return 1;  }</code>
to
<code>if ($a == 0 or $b == 0)  {    return $a+$b; }</code>
and you can omit 
<code>if ($a == 0 && $b == 0)  {    return 0;     }</code>

Regards
Joachim

**Comment by PhilippImhof** [comment]
Thanks for reporting this. You are right, this is a bug, we will fix it in an upcoming release.
