### ISSUE TITLE
"Exception 5" after upgrading Moodle from 3.11 to 4.1

### ISSUE THREAD

**Issue by FloMiLe** [dbauer-ets/moodle-qtype_formulas#90]
## Description of bug / unexpected behavior

After upgrading Moodle from 3.11 to 4.1, I found that Formulas questions cause errors in the question bank.

As soon as an affected Formulas question is listed, a warning box occurs in the "Needs checking?" column that reads: "Exception - 5: Some expressions cannot be evaluated numerically." Below that question, no further questions are listed.

One can get rid of this warning box by opening the question for editing and saving it without actually making any changes. Back in the question bank, that specific question then gets listed without an error, and the next affected questions shows the warning and prevents listing of any further questions.

I hope I could describe this issue properly. – I don't know whether this a bug with Formulas or Moodle itself, but I only seem to see this problem with Formulas questions.

## Expected behavior

There should not be those warning boxes, i.e. all questions should be upgraded to Moodle 4.1 without any errors.

## How to reproduce the issue

1. Start with several Formulas questions in Moodle 3.11.
2. Upgrade Moodle to 4.1.
3. Open question bank.
4. See error.

<details><summary>Screenshots</summary>

<img width="1159" alt="Screen Shot 2023-04-24 at 22 09 33" src="https://user-images.githubusercontent.com/13892710/234105319-28565eb7-a834-46e5-8de5-eecd2cdc4f1e.png">

</details>

## Environment

<details><summary>System Details</summary>

* Moodle version: 4.1.3
* Plugin version: 5.2.1
* PHP version: 8.0.28
* Browser: Safari/Firefox

</details>

**Comment by FloMiLe** [comment]
I rather think this is a general issue. Sorry for posting it here!

See instead: https://moodle.org/mod/forum/discuss.php?d=446066

**Comment by PhilippImhof** [comment]
Thanks for reporting this, Florian. Maybe you could still export that question, preferably from 3.11 and send it to me as a Moodle XML. I would like to have a look at it, to make sure it's not a problem with the plugin.

What is very strange is that the error magically disappears even if you don't change the question.

**Comment by FloMiLe** [comment]
Sorry, I cannot go back to 3.11 at the moment. But it definitely does not have anything to do with Formulas. It's just that I mostly saw it with Formulas questions because they heavily dominate my question bank. ;-)

Tim Hunt over at the Moodle forum suggested a work-around: disabling the question statistics plugin on Admin -> Plugins -> Question bank plugins -> Manage question bank plugins removes the error and allows for listing of all questions.

**Comment by PhilippImhof** [comment]
OK, fine. Thanks a lot & have a nice day.

**Comment by PhilippImhof** [comment]
Would you maybe still send me the XML? What I find very intriguing is that the error message is one of ours...
