### ISSUE TITLE
Error while exporting private data

### ISSUE THREAD

**Issue by ewallah** [dbauer-ets/moodle-qtype_formulas#91]
## Description of bug / unexpected behavior

During the export of private data, I get this error:

An exception occurred while calling mod_quiz\privacy\provider::export_user_data.
This means that the mod_quiz plugin has not finished processing data. The exception information is shown below. They can be sent to the plugin developer.

5: Variable "A" is not defined. in substitute_vname_by_variables
```

#0 /question/type/formulas/question.php(710): qtype_formulas\variables->evaluate_assignments(Object(stdClass), '@5 = @0; @6 = @...')
#1 /question/type/formulas/question.php(178): qtype_formulas_question->get_global_variables()
#2 /question/classes/privacy/provider.php(200): qtype_formulas_question->format_generalfeedback(Object(question_attempt))
#3 /mod/quiz/classes/privacy/provider.php(524): core_question\privacy\provider::export_question_usage($userid, Object(context_module), Array, 33051, Object(mod_quiz_display_options), true)
#4 /mod/quiz/classes/privacy/provider.php(336): mod_quiz\privacy\provider::export_quiz_attempts(Object(core_privacy\local\request\approved_contextlist))
#5 /lib/moodlelib.php(8139): mod_quiz\privacy\provider::export_user_data(Object(core_privacy\local\request\approved_contextlist))
#6 /privacy/classes/manager.php(578): component_class_callback('mod_quiz\\privac...', 'export_user_dat...', Array)
#7 /privacy/classes/manager.php(611): core_privacy\manager::component_class_callback('mod_quiz', 'core_privacy\\lo...', 'export_user_dat...', Array)
#8 /privacy/classes/manager.php(339): core_privacy\manager->handled_component_class_callback('mod_quiz', 'core_privacy\\lo...', 'export_user_dat...', Array)
#9 /admin/tool/dataprivacy/classes/task/process_data_request_task.php(114): core_privacy\manager->export_user_data(Object(core_privacy\local\request\contextlist_collection))
#10 /lib/cronlib.php(359): tool_dataprivacy\task\process_data_request_task->execute()
#11 /lib/cronlib.php(198): cron_run_inner_adhoc_task(Object(tool_dataprivacy\task\process_data_request_task))
#12 /lib/cronlib.php(76): cron_run_adhoc_tasks(1682511421)
#13 /admin/cli/cron.php(178): cron_run()
```

I do not get an error when I preview the question.

## Environment

<details><summary>System Details</summary>

* Moodle version: 4.1.1+ (Build: 20230217)
* Plugin version: 2023021500
* PHP version: 8.0.28
* Browser: na

</details>

## Additional comments

Just following the advice "The exception information is shown below. They can be sent to the plugin developer."

**Comment by PhilippImhof** [comment]
Thanks for reporting this. Can you please attach the question where this happens?

**Comment by PhilippImhof** [comment]
One thing, just a guess from the error message: is it possible that 
- this question once had a variable `A` which was used in the grading criterion or in the model answer
- the question was answered in a quiz in that state
- and you then updated the question, removing that variable `A`?

**Comment by PhilippImhof** [comment]
Closing this, because it is a consequence of the behaviour described in #93.
